# Generated by Django 3.1.3 on 2020-12-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contet',
            new_name='content',
        ),
    ]
